triplet: "T1"
singlet: "S1"
dump: True
xyz_file: "2tThy.xyz"
zeff_type: "orca"

triplet_json_file: "2tThy_t1_freq_log.json"
triplet_npz_file: "2tThy_t1_freq_mat.npz"
singlet_json_file: "2tThy_s1_freq_log.json"
singlet_npz_file: "2tThy_s1_freq_mat.npz"